name: "Check Flutter versions"
on:
  schedule:
    # Every 24 hours
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  check_versions:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v6

      # Install yq and jq
      - name: Install yq and jq
        run: |
          mkdir -p ~/bin
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O ~/bin/yq
          chmod +x ~/bin/yq
          echo "$HOME/bin" >> $GITHUB_PATH

          sudo apt-get install -y jq curl

      - name: Check for new Flutter versions
        run: sh scripts/update_flutter_versions.sh

      - name: Read Flutter versions
        id: flutter_versions
        run: |
          stable_version=$(yq -r '.images[] | select(.docker_tag == "stable") | .flutter_version' versions.yml)
          beta_version=$(yq -r '.images[] | select(.docker_tag == "beta") | .flutter_version' versions.yml)

          {
            echo "stable_version=$stable_version"
            echo "beta_version=$beta_version"
          } >> "$GITHUB_OUTPUT"

      # Create a Pull Request if there are any changes.
      # This is automatically checked internally
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          commit-message: "chore: Update Flutter to ${{ steps.flutter_versions.outputs.stable_version }} (stable), ${{ steps.flutter_versions.outputs.beta_version }} (beta)"
          title: "chore: Update Flutter to ${{ steps.flutter_versions.outputs.stable_version }} (stable), ${{ steps.flutter_versions.outputs.beta_version }} (beta)"
          branch: "chore/update-flutter-version"
